version: '3.8'

services:
  app-prod:
    container_name: lan-file-distributor_prod
    build:
      context: .
      dockerfile: Dockerfile.prod  # 本番環境用のDockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - ENV=development
      - NAS_PATH=${NAS_PATH}
      - PORT=${PORT}
      - HOST_NAS_PATH=${HOST_NAS_PATH}